### ISSUE TITLE
Context lost in HTML5, xpcall issue?

### ISSUE THREAD

**Issue by Notnasiul** [Insality/defold-event#5]
Hi! We are experiencing issues when triggering events, losing context. It seems that the C code that should handle context might not be working in HTML5? Works perfectly fine on editor and standalone builds, though. 

The console shows this error in the browser:

![imagen](https://github.com/user-attachments/assets/73d0abb9-9dfa-42a4-904e-6667307ae9c9)

Here's the function:

```
---@param self interactable
---@param charging boolean
local function on_energy_state_updated(self, charging)
	if not charging and game_state.energy_level <= 0 then
		if self.user_id then
			release_interactable(self, false)
		end
	end
end
```

and how it's subcribed

`game_events.on_energy_state_updated:subscribe(on_energy_state_updated, self)`

**Comment by Insality** [comment]
Thank you! The reasons seems a different `xpcall` signature in different lua versions, will check and update a library with the same tag

**Comment by Insality** [comment]
@Notnasiul Should be fixed at 9 release, I replaced it fixed version
